apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: cicd-container
          image: zjuchy/cicd:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  type: NodePort
  selector:
    app: cicd
  ports:
    - protocol: TCP
      port: 5000           # Service 的内部端口
      targetPort: 5000     # 容器端口
      nodePort: 30001      # 映射到 kind 节点的端口


